// Regenerates the "## 🎴 Commands Reference" tables in README.md directly
// from utils/commandReference.js — the same single source of truth the
// in-chat .menu command already reads from live at runtime.
//
// WHY THIS EXISTS: commandReference.js's own header comment describes
// itself as "shared with README.md's command tables, so the two can never
// silently drift apart" — but that was only true for the in-chat .menu
// command, which reads commandReference.js live every time someone types
// .menu. README.md's tables are a separate, static Markdown file with no
// runtime templating, so there was nothing actually keeping them in sync;
// they had to be hand-copied and could (and did) drift. This script closes
// that gap the same way commandReference.js closed the original one
// between index.js's menu and the README (see that file's header comment
// for the earlier incident this is the same fix for: the pinned
// ani-chan-bot-commands.txt reference file going stale).
//
// This is a different tool from the older generate_command_reference.js,
// which regex-scans raw source comments across commands/*.js into a
// standalone .txt dump (originally for the WhatsApp-pinned reference file)
// and does not touch README.md or commandReference.js at all.
//
// USAGE: node generate_readme_commands.js
// Run this any time utils/commandReference.js changes — after adding,
// removing, or renaming a public command. It only replaces the content
// between the two HTML comment markers below; everything else in
// README.md (the intro paragraph, Tech Stack section, License, etc.) is
// left untouched.

const fs = require('fs');
const path = require('path');

const README_PATH = path.join(__dirname, 'README.md');
const START_MARKER = '<!-- COMMAND_TABLES_START — auto-generated by generate_readme_commands.js from utils/commandReference.js. Do not hand-edit below this line; run `node generate_readme_commands.js` instead. -->';
const END_MARKER = '<!-- COMMAND_TABLES_END -->';

const { COMMAND_REFERENCE } = require('./utils/commandReference.js');

// Markdown table cells break on a raw "|" (e.g. ".deck [add|remove|clear]"
// or ".meme <text>"'s "use | for top|bottom text") — needs escaping to
// "\|" or it truncates the row instead of rendering the character.
function escapeForTable(text) {
  return text.replace(/\|/g, '\\|');
}

function buildTablesMarkdown() {
  return COMMAND_REFERENCE.map(section => {
    const rows = section.items
      .map(item => `| \`${escapeForTable(item.cmd)}\` | ${escapeForTable(item.desc)} |`)
      .join('\n');
    const note = section.note ? `${section.note}\n\n` : '';
    return `### ${section.emoji} ${section.title}\n${note}| Command | Description |\n|---|---|\n${rows}`;
  }).join('\n\n');
}

function main() {
  const readme = fs.readFileSync(README_PATH, 'utf8');

  const startIdx = readme.indexOf(START_MARKER);
  const endIdx = readme.indexOf(END_MARKER);

  if (startIdx === -1 || endIdx === -1 || endIdx < startIdx) {
    throw new Error(
      'Could not find the COMMAND_TABLES_START/END markers in README.md — ' +
      'has the Commands Reference section been restructured? Add the markers ' +
      'back around the command tables and re-run this script.'
    );
  }

  const before = readme.slice(0, startIdx + START_MARKER.length);
  const after = readme.slice(endIdx);
  const tables = buildTablesMarkdown();

  const updated = `${before}\n\n${tables}\n\n${after}`;

  if (updated === readme) {
    console.log('✅ README.md command tables already match utils/commandReference.js — no changes needed.');
    return;
  }

  fs.writeFileSync(README_PATH, updated, 'utf8');
  console.log('✅ README.md command tables regenerated from utils/commandReference.js.');
}

main();
